[package]
name = "launcher"
version = "1.0.0"
authors = []

[addresses]
launcher = "61cd244d871bdc173b1646470773642034f5ef4ccab5c0cf5b137672c5c386d1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"