[package]
name = "launcher"
version = "1.0.0"
authors = []

[addresses]
launcher = "2d7a05530201bb1f23b7ef0c16bdea7c01485a0d486f876d29c5ceff8d3e63a1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"