[package]
name = "launcher"
version = "1.0.0"
authors = []

[addresses]
launcher = "ada1ba057609f6da7e9ea31021a30217b0d125bd3217cba2950f1f61204f1ee2"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"